serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "${resource_identity}"
args:
  - "--tags=$(TAGS)"
  - "--apikey=$(NP_API_KEY)"
  - "--runtime=host"
  - "--command-executor-env=NP_API_KEY=$(NP_API_KEY),VAULT_ADDR=$(VAULT_URL),VAULT_TOKEN=$(VAULT_TOKEN)"
  - "--command-executor-debug"
  - "--webserver-enabled"
  - "--command-executor-git-command-repos $(AGENT_REPOS)"
configuration:
  values:
    NP_API_KEY: "${np_api_key}"
    TAGS: "${tags}"
    AGENT_REPOS: "${agent_repos}"
    CLUSTER_NAME: "${cluster_name}"
    NAMESPACE: "${namespace}"
    VAULT_TOKEN: "${vault_token}"
    VAULT_URL: "${vault_url}"
initScripts:
  - apk add --no-cache curl ca-certificates bash openssl aws-cli gettext gomplate jq yq go
%{ for script in init_scripts ~}
  - ${script}
%{ endfor ~}
image:
  tag: rc
resources:
  requests:
    memory: "${agent_memory_request}"
  limits:
    memory: "${agent_memory_limit}"