serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "${resource_identity}"
args:
  - "--tags=$(TAGS)"
  - "--apikey=$(NP_API_KEY)"
  - "--runtime=host"
  - "--command-executor-env=NP_API_KEY=$(NP_API_KEY),VAULT_ADDR=$(VAULT_URL),VAULT_TOKEN=$(VAULT_TOKEN)"
  - "--command-executor-debug"
  - "--webserver-enabled"
  - "--command-executor-git-command-repos https://$(GITHUB_TOKEN)@$(GITHUB_REPO)#$(GITHUB_BRANCH),https://$(GITHUB_TOKEN)@github.com/galicia-nullplataform/services-provisioner.git#$(GITHUB_BRANCH)"
configuration:
  values:
    NP_API_KEY: "${np_api_key}"
    TAGS: "${tags}"
    GITHUB_USER: "${github_user}"
    GITHUB_TOKEN: "${github_token}"
    GITHUB_REPO: "${github_repo}"
    CLUSTER_NAME: "${cluster_name}"
    NAMESPACE: "${namespace}"
    VAULT_TOKEN: "${vault_token}"
    VAULT_URL: "${vault_url}"
initScripts:
  - apk add --no-cache curl ca-certificates bash openssl aws-cli gettext gomplate jq yq go
%{ for script in init_scripts ~}
  - ${script}
%{ endfor ~}
image:
  tag: rc
