serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "${resource_identity}"
configuration:
  values:
    NP_API_KEY: "${np_api_key}"
    TAGS: "${tags}"
    GITHUB_USER: "${github_user}"
    GITHUB_TOKEN: "${github_token}"
    GITHUB_REPO: "${github_repo}"
    CLUSTER_NAME: "${cluster_name}"
    NAMESPACE: "${namespace}"
initScripts:
  - apk add --no-cache curl ca-certificates bash openssl aws-cli gettext gomplate jq yq go
%{ for script in init_scripts ~}
  - ${script}
%{ endfor ~}