name: ci
on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - 'feature/*'
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Fetch Main Branch
        # Fetches the main branch to ensure it's available for comparison
        run: |
          git fetch origin main:refs/remotes/origin/main --depth=1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7  # Replace with your desired Terraform version
      
      - name: Get terraform-docs
        run: |
          curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.19.0/terraform-docs-v0.19.0-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          mv terraform-docs /terraform-docs

      - name: Validate Terraform modules
        run: |
          set +e  # Disable immediate exit on error
          FAILED=0
          TF_DIRS=$(git diff --name-only origin/main HEAD | xargs -n1 dirname | sort -u)
          for DIR in $TF_DIRS; do
            echo "Validating Terraform in directory: $DIR"
            (cd $DIR; terraform fmt -check)
            if [ $? -ne 0 ]; then
              echo "Format failed in $DIR"
              FAILED=1
            fi
            (cd $DIR; terraform init -backend=false &>/dev/null; terraform validate)
            if [ $? -ne 0 ]; then
              echo "Validation failed in $DIR"
              FAILED=1
            fi
            (cd $DIR; terraform-docs markdown table . --hide header --hide providers --sort-by-required >> README.md)
            if [ -n "$(git diff --name-only .)" ]; then
              echo "Error: There are undocummented repositories changes in the repository."
              exit 1
            else
              echo "No uncommitted changes found."
            fi
          done

          if [ $FAILED -ne 0 ]; then
            exit 1  # Exit with error if any validation failed
          fi
